#!/usr/bin/python
# -*- coding: utf-8 -*-

#Top-level function. Specify the corpus, language, and order for all of the analyses

analysisName = "noFilter_25Feb"
inputDir = "/shared_hd0/corpora/" 
fastStorageDir = "/shared_ssd/ss/"
slowStorageDir = "/shared_hd1/ss/" 

import os, subprocess, re, sys, itertools, codecs, gzip, glob, unicodedata, click, pandas, srilm, pdb, json, multiprocessing, time, tempfile, math, scipy, warnings
#os.chdir('/home/stephan/python/ngrok') #necessary if running from the REPL
import ngrok
#reload(ngrok)


print('Checking for dependencies...')
dependencies = ['ngram','ngram-count','zs','gzrecover']
[ngrok.checkForBinary(d) for d in dependencies]

corporaToAnalyze = [
# {'corpus':'GoogleBooks2012',
# 	'language':'eng-all',
# 	'order':'3',
#  	'target':'3',
# 	'analysisname': analysisName,
# 	'inputdir':inputDir,
# 	'faststoragedir': fastStorageDir,
# 	'slowstoragedir': slowStorageDir,		
# 	'filterlist': None,
# 	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/en/00_lexicalSurprisal/unigram_list.txt',
# 	'retrievalcount':25000,
# 	'modellist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',	
# 	'modelcount':25000,
# 	'dictionary_filter': 'lowerInDictionary',
# 	'country_code': 'en'},
# {'corpus':'GoogleBooks2012',
# 	'language':'spa-all',
# 	'order':'3',
#  	'target':'3',
# 	'analysisname': analysisName,
# 	'inputdir':inputDir,
# 	'faststoragedir': fastStorageDir,
# 	'slowstoragedir': slowStorageDir,
# 	'filterlist':None,
# 	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_es_2013.txt',
# 	'retrievalcount':25000,
# 	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_es_2013.txt',
# 	'modelcount':25000,
# 	'dictionary_filter': 'lowerInDictionary',
# 	'country_code': 'es'},
# {'corpus':'GoogleBooks2012',
# 	'language':'fre-all',
# 	'order':'3',
#  	'target':'3',
# 	'analysisname': analysisName,
# 	'inputdir':inputDir,
# 	'faststoragedir': fastStorageDir,
# 	'slowstoragedir': slowStorageDir,
# 	'filterlist':None,
# 	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_fr_2013.txt',
# 	'retrievalcount':25000,
# 	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_fr_2013.txt',
# 	'modelcount':25000,
# 	'dictionary_filter': 'lowerInDictionary',
# 	'country_code': 'fr'},
# {'corpus':'GoogleBooks2012',
# 	'language':'ger-all',
# 	'order':'3',
#  	'target':'3',
# 	'analysisname': analysisName,
# 	'inputdir':inputDir,
# 	'faststoragedir': fastStorageDir,
# 	'slowstoragedir': slowStorageDir,
# 	'filterlist':None,
# 	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_de_2013.txt',
# 	'retrievalcount':25000,
# 	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_de_2013.txt',
# 	'modelcount':25000,
# 	'dictionary_filter': 'inDictionary',
# 	'country_code': 'de'},
# {'corpus':'GoogleBooks2012',
# 	'language':'rus-all', 
# 	'order':'3',
# 	'target':'3',
# 	'analysisname': analysisName,
# 	'inputdir':inputDir,
# 	'faststoragedir': fastStorageDir,
# 	'slowstoragedir': slowStorageDir,
# 	'filterlist':None,
# 	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ru_2013.txt',
# 	'retrievalcount':25000,
# 	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ru_2013.txt',
# 	'modelcount':25000,
# 	'dictionary_filter': 'lowerInDictionary',
# 	'country_code': 'ru'},
# {'corpus':'GoogleBooks2012',
# 	'language':'heb-all',
# 	'order':'3',
# 	'target':'3',
# 	'analysisname': analysisName,
# 	'inputdir':inputDir,
# 	'faststoragedir': fastStorageDir,
# 	'slowstoragedir': slowStorageDir,
# 	'filterlist':None,
# 	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_he_2013.txt',
# 	'retrievalcount':25000,
# 	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_he_2013.txt',
# 	'modelcount':25000,
# 	'dictionary_filter': 'lowerInDictionary',
# 	'country_code': 'he'},	
{'corpus':'Google1T',
 	'language':'ENGLISH',
 	'order':'3',
 	'target':'3',
 	'analysisname': analysisName,
 	'inputdir':inputDir,
 	'faststoragedir': fastStorageDir,
 	'slowstoragedir': slowStorageDir,
 	'filterlist':None,
 	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',
 	'retrievalcount':25000,
 	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',	
 	'modelcount':25000,
 	'dictionary_filter': 'lowerInDictionary',
 	'country_code': 'en'},
{'corpus':'Google1T',
	'language':'SPANISH',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_es_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_es_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'es'},
{'corpus':'Google1T',
	'language':'FRENCH',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_fr_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_fr_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'fr'},
{'corpus':'Google1T',
	'language':'DUTCH',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_nl_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_nl_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'nl'},
{'corpus':'Google1T',
	'language':'CZECH',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_cs_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_cs_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'cs'},
{'corpus':'Google1T',
	'language':'ROMANIAN',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ro_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ro_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'ro'},
{'corpus':'Google1T',
	'language':'POLISH',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pl_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pl_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pl'},
{'corpus':'Google1T',
	'language':'PORTUGUESE',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pt_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pt_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pt-BR'},
{'corpus':'Google1T',
	'language':'ITALIAN',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_it_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_it_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'it'},
 {'corpus':'Google1T',
 	'language':'SWEDISH',
 	'order':'3',
	'target':'3',
 	'analysisname': analysisName,
 	'inputdir':inputDir,
 	'faststoragedir': fastStorageDir,
 	'slowstoragedir': slowStorageDir,
 	'filterlist':None,
 	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_sv_2013.txt',
 	'retrievalcount':25000,
 	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_sv_2013.txt',	
 	'modelcount':25000,
 	'dictionary_filter': 'lowerInDictionary',
 	'country_code': 'sv'},
{'corpus':'Google1T',
	'language':'GERMAN',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_de_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_de_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'de'},		
  {'corpus': 'BNC',
	'language':'eng',
	'order':'3',
 	'target':'3',
	'inputdir':inputDir,
	'filename': 'BNC_merged.txt',
	'analysisname': analysisName,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'en'},
{'corpus': 'BNC',
	'language':'eng-half',
	'order':'3',
 	'target':'3',
	'inputdir':inputDir,
	'filename': 'BNC_merged_half.txt',
	'analysisname': analysisName,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'en'},
{'corpus':'OPUS',
	'language':'en',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,		
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',
	'retrievalcount':25000,
	'modellist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_en_2013.txt',	
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'en',
	'filename':'OPUS_en.txt'},
{'corpus':'OPUS',
	'language':'es',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_es_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_es_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'es',
	'filename':'OPUS_es.txt'},
{'corpus':'OPUS',
	'language':'fr',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_fr_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_fr_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'fr',
	'filename':'OPUS_fr.txt'},
{'corpus':'OPUS',
	'language':'de',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_de_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_de_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'de',
	'filename':'OPUS_de.txt'},
{'corpus':'OPUS',
	'language':'ru', 
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ru_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ru_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'ru',
	'filename':'OPUS_ru.txt'},
{'corpus':'OPUS',
	'language':'he',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_he_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_he_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'he',
	'filename':'OPUS_he.txt'},	
{'corpus':'OPUS',
	'language':'cs',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_cs_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_cs_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'cs',
	'filename':'OPUS_cs.txt'},	
{'corpus':'OPUS',
	'language':'pl',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pl_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pl_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pl',
	'filename':'OPUS_pl.txt'},	
{'corpus':'OPUS',
	'language':'ro',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ro_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_ro_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'ro',
	'filename':'OPUS_ro.txt'},
{'corpus':'OPUS',
	'language':'sv',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_sv_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_sv_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'sv',
	'filename':'OPUS_sv.txt'},
{'corpus':'OPUS',
	'language':'nl',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_nl_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_nl_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'nl',
	'filename':'OPUS_nl.txt'},
{'corpus':'OPUS',
	'language':'pt',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pt_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_pt_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pt',
	'filename':'OPUS_pt.txt'},				
{'corpus':'OPUS',
	'language':'it',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_it_2013.txt',
	'retrievalcount':25000,
	'modellist': '/shared_hd0/corpora/OPUS/2013_OPUS/noFilter_it_2013.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'it',
	'filename':'OPUS_it.txt'}	
]

if __name__ == '__main__':
    #[ngrok.downloadCorpus(x) for x in corporaToAnalyze]	    
    #[ngrok.validateCorpus(x) for x in corporaToAnalyze]    
    [ngrok.analyzeCorpus(x) for x in corporaToAnalyze]
